export const frontendProjects = [
  {
    id: 1,
    title: "Apple UI Clone",
    logo: "https://cdn.freelogovectors.net/wp-content/uploads/2023/03/apple_logo-freelogovectors.net_-1.png",
    category: "Frontend",
    primaryColor: "#007AFF",
    secondaryColor: "#5856D6",
    subdescription: "iPhone 15 launch website clone using 3D models and animations.",
    description:
      "A stunning recreation of the iPhone 15 launch website using React, GSAP, and Three.js. Features smooth transitions, 3D visuals, and a focus on visual storytelling to mimic the Apple user experience.",
    techStack: [
      { name: "React", color: "bg-blue-500" },
      { name: "TailwindCSS", color: "bg-cyan-500" },
      { name: "GSAP", color: "bg-green-500" },
      { name: "Three.js", color: "bg-purple-500" },
    ],
    features: ["3D iPhone Models", "Smooth Scroll Animations", "Responsive Design", "Interactive Elements"],
    metrics: {
      performance: "95%",
      accessibility: "92%",
      bestPractices: "98%",
      seo: "90%",
    },
    liveLink: "https://appple-clone-harman.netlify.app/",
    githubLink: "https://github.com/Harman8815/Apple-UI",
    status: "Completed",
    difficulty: "Advanced",
    duration: "3 weeks",
    highlights: ["Award-winning Design", "3D Integration", "Performance Optimized"],
  },
  {
    id: 2,
    title: "Portfolio Website",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpd4mJRIUwqgE8D_Z2znANEbtiz4GhI4M8NQ&s",
    category: "Frontend",
    primaryColor: "#FF6B35",
    secondaryColor: "#F7931E",
    subdescription: "Responsive personal portfolio with animations and dark mode.",
    description:
      "A modern and fully responsive developer portfolio built with React, TailwindCSS, GSAP, and Three.js. Includes animated sections, a 3D About Me component, and support for light/dark mode toggling.",
    techStack: [
      { name: "React", color: "bg-blue-500" },
      { name: "Three.js", color: "bg-purple-500" },
      { name: "TailwindCSS", color: "bg-cyan-500" },
      { name: "GSAP", color: "bg-green-500" },
    ],
    features: ["3D Interactive Elements", "Dark/Light Mode", "Smooth Animations", "Mobile Responsive"],
    metrics: {
      performance: "98%",
      accessibility: "95%",
      bestPractices: "100%",
      seo: "95%",
    },
    liveLink: "https://portfolioharman-react.netlify.app/",
    githubLink: "#",
    status: "Live",
    difficulty: "Intermediate",
    duration: "2 weeks",
    highlights: ["3D Graphics", "Performance Focused", "Modern Design"],
  },
  {
    id: 3,
    title: "Zentry Clone",
    logo: "https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/151113782034/original/1FWLSjPmqXjuOhNM1gBpXgtda55-D2BnnQ.png",
    category: "Frontend",
    primaryColor: "#8B5CF6",
    secondaryColor: "#A855F7",
    subdescription: "A frontend UI clone inspired by a productivity dashboard.",
    description:
      "A visually dynamic frontend-only clone of Zentry's homepage UI. Features smooth scroll animations, custom components, and utility-first layout powered by TailwindCSS and GSAP.",
    techStack: [
      { name: "React", color: "bg-blue-500" },
      { name: "TailwindCSS", color: "bg-cyan-500" },
      { name: "GSAP", color: "bg-green-500" },
    ],
    features: ["Scroll Animations", "Custom Components", "Responsive Layout", "Modern UI/UX"],
    metrics: {
      performance: "94%",
      accessibility: "90%",
      bestPractices: "96%",
      seo: "88%",
    },
    liveLink: "https://zentri-clone.netlify.app/",
    githubLink: "https://github.com/Harman8815/Zentry-animated-website",
    status: "Completed",
    difficulty: "Intermediate",
    duration: "1.5 weeks",
    highlights: ["Pixel Perfect", "Animation Heavy", "UI Clone"],
  },
  {
    id: 4,
    title: "Sundown Studio Clone",
    logo: "https://assets-global.website-files.com/64d3dd9edfb41666c35b15b7/64d3dd9edfb41666c35b15c2_Sundown%20logo.svg",
    category: "Frontend",
    primaryColor: "#F59E0B",
    secondaryColor: "#D97706",
    subdescription: "Creative agency site clone with scroll-based animations.",
    description:
      "A visually rich animated website inspired by Sundown Studio. Built using vanilla JS and GSAP for scroll-triggered animations and transitions to highlight creative storytelling.",
    techStack: [
      { name: "HTML5", color: "bg-orange-500" },
      { name: "CSS3", color: "bg-blue-500" },
      { name: "JavaScript", color: "bg-yellow-500" },
      { name: "GSAP", color: "bg-green-500" },
    ],
    features: ["Scroll Triggers", "Creative Animations", "Vanilla JavaScript", "Performance Optimized"],
    metrics: {
      performance: "96%",
      accessibility: "88%",
      bestPractices: "94%",
      seo: "85%",
    },
    liveLink: "https://sundown-website-clone.netlify.app/",
    githubLink: "https://github.com/Harman8815/Sundown-animated-website",
    status: "Completed",
    difficulty: "Advanced",
    duration: "2 weeks",
    highlights: ["Creative Design", "Vanilla JS", "Animation Master"],
  },
  {
    id: 5,
    title: "3D T-Shirt Customizer",
    logo: "https://i.pinimg.com/736x/55/97/a9/5597a9e2ad98912f550e2719cd673d6b.jpg",
    category: "Frontend",
    primaryColor: "#10B981",
    secondaryColor: "#059669",
    subdescription: "Interactive t-shirt customization experience using 3D models.",
    description:
      "A fully interactive 3D product customization page built with React Three Fiber and Tailwind. Users can change shirt colors, upload logos, and view real-time 3D previews.",
    techStack: [
      { name: "React", color: "bg-blue-500" },
      { name: "Three.js", color: "bg-purple-500" },
      { name: "TailwindCSS", color: "bg-cyan-500" },
      { name: "R3F", color: "bg-pink-500" },
    ],
    features: ["3D Product View", "Real-time Customization", "Color Picker", "Logo Upload"],
    metrics: {
      performance: "92%",
      accessibility: "89%",
      bestPractices: "95%",
      seo: "82%",
    },
    liveLink: "https://3d-tshirt-editter.netlify.app/",
    githubLink: "https://github.com/Harman8815/tshirt-3d-website",
    status: "Completed",
    difficulty: "Advanced",
    duration: "2.5 weeks",
    highlights: ["3D Interaction", "Real-time Preview", "E-commerce Ready"],
  },
]

export const fullstackProjects = [
  {
    id: 6,
    title: "Gmail Clone",
    logo: "https://images.icon-icons.com/2642/PNG/512/google_mail_gmail_logo_icon_159346.png",
    category: "Fullstack",
    primaryColor: "#EA4335",
    secondaryColor: "#FBBC04",
    subdescription: "Full-featured email client with real-time synchronization.",
    description:
      "A comprehensive Gmail clone built with Firebase and React. Includes real-time mailbox sync, user authentication, routing, and responsive layout that closely mimics the Gmail experience.",
    techStack: [
      { name: "React", color: "bg-blue-500" },
      { name: "Firebase", color: "bg-orange-500" },
      { name: "Firestore", color: "bg-yellow-500" },
      { name: "EmailJS", color: "bg-green-500" },
    ],
    features: ["Real-time Email Sync", "User Authentication", "Compose & Send", "Email Threading"],
    metrics: {
      performance: "89%",
      accessibility: "92%",
      bestPractices: "94%",
      seo: "87%",
    },
    liveLink: "#",
    githubLink: "https://github.com/Harman8815/Gmail-Clone",
    status: "In Development",
    difficulty: "Advanced",
    duration: "4 weeks",
    highlights: ["Real-time Sync", "Firebase Integration", "Email Client"],
  },
  {
    id: 7,
    title: "Harvest Horizon",
    logo: "https://t4.ftcdn.net/jpg/06/43/74/99/360_F_643749925_2y3oCguT4NLWJqOFSfUIDYk4rLQJEwu6.jpg",
    category: "Fullstack",
    primaryColor: "#16A34A",
    secondaryColor: "#15803D",
    subdescription: "AI-powered crop prediction and monitoring system.",
    description:
      "A machine learning–powered crop prediction system that analyzes yield and health status. Built using a Python Flask backend and integrated with an Express/React-based frontend dashboard.",
    techStack: [
      { name: "React", color: "bg-blue-500" },
      { name: "Express", color: "bg-gray-600" },
      { name: "MongoDB", color: "bg-green-600" },
      { name: "Python Flask", color: "bg-blue-600" },
      { name: "ML", color: "bg-purple-500" },
    ],
    features: ["Crop Prediction", "Health Monitoring", "ML Analytics", "Farmer Dashboard"],
    metrics: {
      performance: "91%",
      accessibility: "88%",
      bestPractices: "93%",
      seo: "85%",
    },
    liveLink: "https://harvest-horizon.onrender.com/",
    githubLink: "https://github.com/Harman8815/Harvest-Horizon",
    status: "Live",
    difficulty: "Expert",
    duration: "6 weeks",
    highlights: ["AI/ML Integration", "Agriculture Tech", "Data Analytics"],
  },
  {
    id: 8,
    title: "DGA Domain Detection",
    logo: "https://images.seeklogo.com/logo-png/32/1/dga-logo-png_seeklogo-327455.png",
    category: "Fullstack",
    primaryColor: "#DC2626",
    secondaryColor: "#B91C1C",
    subdescription: "Cybersecurity system for detecting malicious domain generation.",
    description:
      "An Intrusion Detection System that identifies DGA-based attacks using metadata and ML classification. Combines Python backend models with a React-powered visualization dashboard for real-time alerts.",
    techStack: [
      { name: "React", color: "bg-blue-500" },
      { name: "Python", color: "bg-blue-600" },
      { name: "Scikit-learn", color: "bg-orange-500" },
      { name: "Flask", color: "bg-gray-600" },
      { name: "ML", color: "bg-purple-500" },
    ],
    features: ["DGA Detection", "Real-time Alerts", "ML Classification", "Security Dashboard"],
    metrics: {
      performance: "94%",
      accessibility: "90%",
      bestPractices: "96%",
      seo: "88%",
    },
    liveLink: "https://dgadetection-harman.netlify.app/",
    githubLink: "#",
    status: "Completed",
    difficulty: "Expert",
    duration: "5 weeks",
    highlights: ["Cybersecurity", "ML Detection", "Real-time Monitoring"],
  },
  {
    id: 9,
    title: "Admin Dashboard Pro",
    logo: "https://t4.ftcdn.net/jpg/02/27/45/09/360_F_227450952_KQCMShHPOPebUXklULsKsROk5AvN6H1H.jpg",
    category: "Fullstack",
    primaryColor: "#7C3AED",
    secondaryColor: "#6D28D9",
    subdescription: "Comprehensive admin panel with analytics and management tools.",
    description:
      "A modular admin dashboard featuring student progress tracking, integrated calendar, task whiteboard, and data visualizations. Built with SCSS for styling and MongoDB as the primary datastore.",
    techStack: [
      { name: "React", color: "bg-blue-500" },
      { name: "SCSS", color: "bg-pink-500" },
      { name: "Node.js", color: "bg-green-600" },
      { name: "MongoDB", color: "bg-green-600" },
    ],
    features: ["Student Tracking", "Calendar Integration", "Task Management", "Data Visualization"],
    metrics: {
      performance: "93%",
      accessibility: "91%",
      bestPractices: "95%",
      seo: "89%",
    },
    liveLink: "https://admin-dashboard-harman.netlify.app/",
    githubLink: "https://github.com/Harman8815/Admin-Dashboard",
    status: "Live",
    difficulty: "Advanced",
    duration: "4 weeks",
    highlights: ["Admin Panel", "Data Visualization", "Task Management"],
  },
  {
    id: 10,
    title: "Project Management System",
    logo: "https://images-platform.99static.com//979ew2eYmqF1PQhuf9MFQTjWn84=/0x0:1058x1058/fit-in/500x500/projects-files/49/4991/499142/20cfa402-5689-4eea-be2e-08406663e87d.jpg",
    category: "Fullstack",
    primaryColor: "#0EA5E9",
    secondaryColor: "#0284C7",
    subdescription: "Enterprise-grade project and team management platform.",
    description:
      "A fullstack task management platform built with Next.js. Includes JWT-based authentication, protected routes, PostgreSQL for persistence, and a role-based team management interface.",
    techStack: [
      { name: "Next.js", color: "bg-black" },
      { name: "Node.js", color: "bg-green-600" },
      { name: "PostgreSQL", color: "bg-blue-600" },
      { name: "JWT", color: "bg-red-500" },
    ],
    features: ["Team Management", "Task Tracking", "Role-based Access", "Real-time Updates"],
    metrics: {
      performance: "95%",
      accessibility: "93%",
      bestPractices: "97%",
      seo: "91%",
    },
    liveLink: "#",
    githubLink: "https://github.com/Harman8815/Project-Management",
    status: "In Development",
    difficulty: "Expert",
    duration: "8 weeks",
    highlights: ["Enterprise Grade", "Team Collaboration", "Scalable Architecture"],
  },
]

// Combined projects for easy access
export const allProjects = [...frontendProjects, ...fullstackProjects]

// Project statistics
export const projectStats = {
  total: allProjects.length,
  frontend: frontendProjects.length,
  fullstack: fullstackProjects.length,
  completed: allProjects.filter((p) => p.status === "Completed").length,
  live: allProjects.filter((p) => p.status === "Live").length,
  inDevelopment: allProjects.filter((p) => p.status === "In Development").length,
  technologies: [...new Set(allProjects.flatMap((p) => p.techStack.map((t) => t.name)))].length,
  totalDuration: allProjects.reduce((sum, p) => {
    const weeks = Number.parseFloat(p.duration.split(" ")[0])
    return sum + weeks
  }, 0),
}
